### ISSUE TITLE
chinese to english result issue

### ISSUE THREAD

**Issue by sdongchuanqi** [carboncoo/mask-align#6]
I have problem with reproducing the chinese to english result in paper (13.8%) .The best result I did is (14.6%) 
I use the LDC dataset ,do BPE to the train.ch and train.en ,then do suff and then clean the single word sentence .
Using Chinese-English evaluation set for test and dev, I preprocess chinese with BPE , and do nothing with English.
And I use the example config,I modify the path and set batchsize to 5000 and  updatacycle to 2.
I would be grateful,if you can help me to reproduce the result

**Comment by carboncoo** [comment]
Maybe you can try using BPE on English and see what the results would be.
