### ISSUE TITLE
issue on analyzed in your paper 

### ISSUE THREAD

**Issue by sdongchuanqi** [carboncoo/mask-align#8]
I notice the "Predict and Alignment" part in your paper.
You divided tokens into four categories :cPcA wPcA cPwA wPwA。
Can you explain how to calculated them ?

**Comment by carboncoo** [comment]
You can check `scripts/cal_pred_align.py` for the exact calculation process. 

Here is an example of running the script.
```python
python thumt/scripts/cal_pred_align.py \
        exp/agree_deen/test/pred.txt \
        <test_data>/deen.lc.tgt.bpe \
        exp/agree_deen/test/alignment-f.txt \
        <test_data>/deen.talp
```
